### PR TITLE
Update colorbar.rst

### PR DESCRIPTION
**Pull request by springertang**
colorbar with cpt file example

### CODE REVIEW

**Comment by core-man** [comment]
See the color bar:


This example is good. However, I think we would not like to put any input file in the examples for a module, but I don't know where this example should put. Ping @seisman for any comment.

**Comment by seisman** [comment]
I don't think this is a good example. I also don't want to provide any customized CPT, which fully depends on users' tastes.

**Comment by core-man** [comment]
> I don't think this is a good example. I also don't want to provide any customized CPT, which fully depends on users' tastes.

well, close this PR?

**Comment by wangliang1989** [comment]
I like this CPT.

**Pull request closed without merging**
